Repository confluentinc/vscode, pull requests merged in 2025-01, with the labels that each got.

#837 466 enforce setting id for tree view items
  src/commands/schemas.test.ts
  src/models/main.test.ts
  src/models/main.ts
  src/models/schema.test.ts
  src/storage/resourceManager.test.ts
  src/viewProviders/schemas.ts
  src/viewProviders/topics.test.ts
  tests/unit/testResources/kafkaCluster.ts
  tests/unit/testResources/schema.ts
  tests/unit/testResources/schemaRegistry.ts
Labels: cleanup

#948 Updates for scaffold service: client-side form validation
  src/scaffold.ts
  src/webview/scaffold-form.html
  src/webview/scaffold-form.spec.ts
  src/webview/scaffold-form.ts
  src/webview/uikit/uikit.css
Labels: usability

#989 Move ResourceLoader et all to new toplevel package.
  src/commands/schemaUpload.ts
  src/commands/schemas.test.ts
  src/commands/schemas.ts
  src/consume.ts
  src/directConnectManager.ts
  src/extension.ts
  src/loaders/ccloudResourceLoader.ts
  src/loaders/directResourceLoader.ts
  src/loaders/index.ts
  src/loaders/loaderUtils.test.ts
  src/loaders/loaderUtils.ts
  src/loaders/localResourceLoader.ts
  src/loaders/resourceLoader.test.ts
  src/loaders/resourceLoader.ts
  src/loaders/resourceLoaderInitialization.ts
  src/quickpicks/kafkaClusters.ts
  src/quickpicks/schemaRegistries.ts
  src/quickpicks/schemas.ts
  src/quickpicks/topics.ts
  src/viewProviders/resources.ts
  src/viewProviders/schemas.ts
  src/viewProviders/topics.test.ts
  src/viewProviders/topics.ts
Labels: cleanup

#990 Try to harden sidecar starting
  CHANGELOG.md
  src/sidecar/sidecarManager.ts
Labels: cleanup, observability
